### PR TITLE
update youtube regex and entry point in fixture

### PR DESCRIPTION
**Pull request by meako689**
hi from biggggidea :)

### CODE REVIEW

**Comment by kottenator** [comment]
Hi! We had problems with the fixtures too... Sorry, I'm not in WebRiders anymore and can't merge your PR. Have you checked the latest version of the original `django-oembed`?

**Comment by meako689** [comment]
```
                                                                                  No problem, just wanted to say hi :)Original repo doesn't update for years.
```

**Comment by kottenator** [comment]
Yes, you're right. At a glance, [this one](https://github.com/coleifer/micawber) is pretty popular right now

**Comment by meako689** [comment]
thx. Sometimes it's easier to fix what's stopped working than replace it with new, maybe even better solution.

**Comment by kottenator** [comment]
Sure, it's up to you. Why have you declined your PR? I believe that it will be accepted by WebRiders

**Pull request closed without merging**
